# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 07:52
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/profile/')),
                ('nickname', models.CharField(max_length=16, null=True, unique=True, verbose_name='닉네임')),
                ('sex', models.CharField(blank=True, choices=[('1', '남'), ('2', '여')], max_length=2, null=True, verbose_name='성별')),
                ('birth', models.CharField(blank=True, max_length=16, null=True, validators=[accounts.models.birth_validator], verbose_name='생년월일')),
                ('city', models.CharField(blank=True, max_length=16, null=True, verbose_name='시/도')),
                ('district', models.CharField(blank=True, max_length=8, null=True, verbose_name='구')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
