# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0017_auto_20170710_1652'),
        ('accounts', '0003_auto_20170616_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite',
            field=models.ManyToManyField(to='cast.Favorite'),
        ),
    ]
