# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=16, null=True, verbose_name='닉네임'),
        ),
    ]
