# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 10:51
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.CharField(blank=True, default='19000000', max_length=16, null=True, validators=[accounts.models.birth_validator], verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='시/도'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='구'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('1', 'MALE'), ('2', 'FEMALE')], default='1', max_length=2, verbose_name='성별'),
        ),
    ]
