# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170806_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='0', upload_to='%Y/%m/%d/profile/'),
            preserve_default=False,
        ),
    ]
