# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-10 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='cast/img/angry.png', upload_to='%Y/%m/%d/profile/'),
        ),
    ]
