# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('like_number', models.IntegerField(default=0)),
                ('dislike_number', models.IntegerField(default=0)),
                ('recomment_number', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CommentEmotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('0', '선택안함'), ('1', '좋아요'), ('2', '싫어요')], default='0', max_length=2)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_emotion_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Congressman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('profile_image_path', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('party', models.CharField(blank=True, max_length=32, null=True)),
                ('constituency', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('like_number', models.IntegerField(default=0)),
                ('dislike_number', models.IntegerField(default=0)),
                ('comment_number', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CongressmanEmotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('0', '선택안함'), ('1', '좋아요'), ('2', '싫어요')], default='0', max_length=2)),
                ('congressman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='congressman_emotion_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents_type', models.CharField(choices=[('0', '뉴스'), ('1', '영상')], max_length=2, null=True, verbose_name='타입')),
                ('url_path', models.CharField(max_length=128, null=True, verbose_name='컨텐츠URL')),
                ('title', models.CharField(max_length=64, null=True, verbose_name='제목')),
                ('description', models.TextField(max_length=1024)),
                ('comment_number', models.IntegerField(default=0)),
                ('like_number', models.IntegerField(default=0)),
                ('dislike_number', models.IntegerField(default=0)),
                ('surprise_number', models.IntegerField(default=0)),
                ('angry_number', models.IntegerField(default=0)),
                ('laugh_number', models.IntegerField(default=0)),
                ('sad_number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'contents',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContentsEmotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('0', '선택안함'), ('1', '좋아요'), ('2', '싫어요'), ('3', '놀라워요'), ('4', '화나요'), ('5', '웃겨요'), ('6', '슬퍼요')], default='0', max_length=2)),
                ('contents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Contents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents_emotion_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congressman', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman')),
                ('contents', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cast.Contents')),
            ],
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('0', '미시행'), ('1', '진행중'), ('2', '시행완료'), ('3', '시행실패')], max_length=2)),
                ('description', models.TextField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('like_number', models.IntegerField(default=0)),
                ('dislike_number', models.IntegerField(default=0)),
                ('comment_number', models.IntegerField(default=0)),
                ('congressman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman')),
            ],
        ),
        migrations.CreateModel(
            name='PledgeEmotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('0', '선택안함'), ('1', '좋아요'), ('2', '싫어요')], default='0', max_length=2)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Pledge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledge_emotion_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='pledge',
            name='emotion',
            field=models.ManyToManyField(through='cast.PledgeEmotion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorite',
            name='pledge',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cast.Pledge'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contents',
            name='emotion',
            field=models.ManyToManyField(through='cast.ContentsEmotion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='congressman',
            name='emotion',
            field=models.ManyToManyField(through='cast.CongressmanEmotion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='congressman',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
        migrations.AddField(
            model_name='comment',
            name='contents',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cast.Contents'),
        ),
        migrations.AddField(
            model_name='comment',
            name='pledge',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cast.Pledge'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
