# Generated by Django 2.2.2 on 2019-07-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0002_crawlkeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlkeyword',
            name='crawled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
