# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0003_auto_20170616_1636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='Contents',
        ),
        migrations.RenameField(
            model_name='contents',
            old_name='content_type',
            new_name='contents_type',
        ),
    ]
