# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cast', '0004_auto_20170616_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentsEmotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('0', '선택안함'), ('1', '역겨워요'), ('2', '놀라워요'), ('3', '기뻐요'), ('4', '슬퍼요'), ('5', '화나요'), ('6', '멋져요')], max_length=2)),
                ('contents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_contents_set', to='cast.Contents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_user_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contents',
            name='emotion',
            field=models.ManyToManyField(through='cast.ContentsEmotion', to=settings.AUTH_USER_MODEL),
        ),
    ]
