# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 07:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cast', '0005_auto_20170620_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongressmanEmotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('0', '선택안함'), ('1', '좋아요'), ('2', '싫어요')], default='0', max_length=2)),
                ('congressman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='congressman_emotion_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PledgeEmotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('0', '선택안함'), ('1', '좋아요'), ('2', '싫어요')], default='0', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='contentsemotion',
            name='contents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Contents'),
        ),
        migrations.AlterField(
            model_name='contentsemotion',
            name='name',
            field=models.CharField(choices=[('0', '선택안함'), ('1', '역겨워요'), ('2', '놀라워요'), ('3', '기뻐요'), ('4', '슬퍼요'), ('5', '화나요'), ('6', '멋져요')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='contentsemotion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents_emotion_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='congressman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
        migrations.AddField(
            model_name='pledgeemotion',
            name='pledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Pledge'),
        ),
        migrations.AddField(
            model_name='pledgeemotion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledge_emotion_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
