# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cast', '0007_auto_20170621_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('like_dislike', models.CharField(choices=[('0', '선택안함'), ('1', '좋아요'), ('2', '싫어요')], default='0', max_length=2)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='congressmanemotion',
            name='congressman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='congressman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Pledge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cast.Pledge'),
        ),
        migrations.AddField(
            model_name='comment',
            name='congressman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
        migrations.AddField(
            model_name='comment',
            name='contents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cast.Contents'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
