# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0008_auto_20170626_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Pledge',
            new_name='pledge',
        ),
        migrations.AlterField(
            model_name='comment',
            name='congressman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
        migrations.AlterField(
            model_name='congressmanemotion',
            name='congressman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='congressman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
    ]
