# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cast', '0012_auto_20170626_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentEmotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('0', '선택안함'), ('1', '좋아요'), ('2', '싫어요')], default='0', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like_dislike',
        ),
        migrations.AlterField(
            model_name='comment',
            name='congressman',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
        migrations.AlterField(
            model_name='congressmanemotion',
            name='congressman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='congressman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
        migrations.AddField(
            model_name='commentemotion',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Comment'),
        ),
        migrations.AddField(
            model_name='commentemotion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_emotion_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
