# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cast', '0015_auto_20170705_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congressman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contents',
            options={'verbose_name_plural': 'contents'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='congressman',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
        migrations.AlterField(
            model_name='congressmanemotion',
            name='congressman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='congressman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='contents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Contents'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='pledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Pledge'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
