# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0018_auto_20170710_1832'),
        ('cast', '0016_auto_20170709_1057'),
    ]

    operations = [
    ]
