# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0020_auto_20170711_1444'),
        ('cast', '0020_auto_20170711_2036'),
    ]

    operations = [
    ]
