# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0022_auto_20170713_1800'),
        ('cast', '0014_auto_20170705_1551'),
    ]

    operations = [
    ]
