# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0024_auto_20170713_2012'),
        ('cast', '0022_auto_20170713_1558'),
    ]

    operations = [
    ]
