# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0030_auto_20170719_1733'),
        ('cast', '0030_auto_20170719_2350'),
    ]

    operations = [
    ]
