# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0031_merge_20170721_1721'),
        ('cast', '0034_auto_20170724_1828'),
    ]

    operations = [
    ]
