# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0040_auto_20170730_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='recomment_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contents',
            name='comment_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='congressman',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
        migrations.AlterField(
            model_name='congressmanemotion',
            name='congressman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
        migrations.AlterField(
            model_name='contentsemotion',
            name='name',
            field=models.CharField(choices=[('0', '선택안함'), ('1', '좋아요'), ('2', '싫어요'), ('3', '놀라워요'), ('4', '화나요'), ('5', '웃겨요'), ('6', '슬퍼요')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='congressman',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='congressman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
    ]
