# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0043_auto_20170803_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='angry_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contents',
            name='dislike_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contents',
            name='laugh_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contents',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contents',
            name='sad_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contents',
            name='surprise_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='congressman',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
        migrations.AlterField(
            model_name='congressmanemotion',
            name='congressman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='congressman',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='congressman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.Congressman'),
        ),
    ]
