# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CongressMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('profile_image_path', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('party', models.CharField(blank=True, max_length=32, null=True)),
                ('constituency', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('0', '뉴스'), ('1', '영상')], max_length=2, null=True, verbose_name='타입')),
                ('url_path', models.CharField(max_length=128, null=True, verbose_name='컨텐츠URL')),
                ('title', models.CharField(max_length=64, null=True, verbose_name='제목')),
                ('description', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('0', '미시행'), ('1', '진행중'), ('2', '시행완료'), ('3', '시행실패')], max_length=2)),
                ('description', models.TextField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('congressman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.CongressMan')),
            ],
        ),
    ]
