# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 07:36
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0002_content_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='congressman',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pledge',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
