# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackComment',
            new_name='BoardComment',
        ),
    ]
