# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 06:34
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170615_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.CharField(max_length=16, null=True, validators=[accounts.models.birth_validator], verbose_name='생년월일'),
        ),
    ]
